### Importar librería

In [1]:
import pandas as pd

### Cargar DataFrame

In [2]:
df_books = pd.read_csv('C:\\Users\PEDRO\\repositorios\\numpy\\bestsellers-with-categories.csv',sep=',',header=0)
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

### info()

como dice el nombre nos da una informacion completa de los datos de nuestro dataframe

In [3]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

### describe()

DE solo las columans numericas nos da ciertos datos estadisticos  utiles

In [4]:
df_books.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

### head() y tail()

es lo inverso a la funcion head

In [ ]:
df_books.tail(2)

                                                  Name  ...        Genre
548  You Are a Badass: How to Stop Doubting Your Gr...  ...  Non Fiction
549  You Are a Badass: How to Stop Doubting Your Gr...  ...  Non Fiction

[2 rows x 7 columns]

In [ ]:
df_books.head()

                                                Name  ...        Genre
0                      10-Day Green Smoothie Cleanse  ...  Non Fiction
1                                  11/22/63: A Novel  ...      Fiction
2            12 Rules for Life: An Antidote to Chaos  ...  Non Fiction
3                             1984 (Signet Classics)  ...      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  ...  Non Fiction

[5 rows x 7 columns]

### memory_usage()

para saber memoria que ocupan los datos usamos la funcion memory_usage

In [ ]:
df_books.memory_usage(deep=True)

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

### value_counts()

la  funcion value_counts nos muestra cuantos valores tenemos por cada uno de los autores que se encuentran

In [ ]:
df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

### drop_duplicates()

duplicamos la fila 0 para duplicarlo , no es el head

In [41]:
df_books.iloc[0]

Name           10-Day Green Smoothie Cleanse
Author                              JJ Smith
User Rating                              4.7
Reviews                                17350
Price                                      8
Year                                    2016
Genre                            Non Fiction
Name: 0, dtype: object

In [44]:

df_books=pd.concat([df_books,df_books.iloc[0].to_frame().T])

In [46]:
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction

In [ ]:
habia usado esta funcion append, pero no funciono ,

Actualmente no se puede emplear append, por lo que para duplicar una fila expongo la mejor v'ia a mi entender utilizando . concat de pandas. mi base de datos se llama books,
 a continuacion el codigo:

row = books.iloc[0] 
books3 = pd.concat([books,row.to_frame().T], ignore_index = True)

usando' to_frame().T 'se convierte en un DataFrame de una sola fila 
El argumento 'ignore_index=True 'se utiliza para reasignar índices a las filas en el nuevo DataFrame

df_books = df_books.append(df_books.iloc[0],ignore_index=True)

lo que hace keep='last' es dejar el ultimo duplicado y borrar el primero

In [45]:
df_books.drop_duplicates(keep='last')

,Name,Author,User Rating,Reviews,Price,Year,Genre
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
...,...,...,...,...,...,...,...
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction

### sort_values()

sort_values te ordena los valores de la columna y el ascending=false lo que hace es ordenartelo de manera ascendente y alrevez con true (ya viene predeterminado)

In [ ]:
df_books.sort_values('Year',ascending=False)

                                                  Name  ...        Genre
179                       If Animals Kissed Good Night  ...      Fiction
294  School Zone - Big Preschool Workbook - Ages 4 ...  ...  Non Fiction
263    P is for Potty! (Sesame Street) (Lift-the-Flap)  ...  Non Fiction
489                   The Wonderful Things You Will Be  ...      Fiction
267             Player's Handbook (Dungeons & Dragons)  ...      Fiction
..                                                 ...  ...          ...
160                  Have a Little Faith: A True Story  ...  Non Fiction
512                             True Compass: A Memoir  ...  Non Fiction
513               Twilight (The Twilight Saga, Book 1)  ...      Fiction
78   Divine Soul Mind Body Healing and Transmission...  ...  Non Fiction
459        The Shack: Where Tragedy Confronts Eternity  ...      Fiction

[551 rows x 7 columns]